In [1]:
import numpy as np

# NumPy 
NumPy is a Linear Algebra Library in Python and it is the holy grail and the main building block of Data Science using Python. Almost all the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

It is bound to several C libraries which makes NumPy one of the fastest libraries in Python.

We will learn the basics of NumPy, to get started we need to install it!

In [3]:
empty_arr= np.arr[]

SyntaxError: invalid syntax (389043996.py, line 1)

In [4]:
empty_arr= np.array([])

In [6]:
type(empty_arr)

numpy.ndarray

In [7]:
empty_arr

array([], dtype=float64)

In [8]:
my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [9]:
tup1 = (54,34,22)
np.array(tup1)

array([54, 34, 22])

In [10]:
type(tup1)

tuple

In [11]:
a=np.array(tup1)
type(a)

numpy.ndarray

In [12]:
a

array([54, 34, 22])

In [14]:
a=np.array(my_list)
a

array([1, 2, 3, 4, 5])

In [15]:
type(a)

numpy.ndarray

In [16]:
type(a)   # ndarray is number dimension array

numpy.ndarray

In [17]:
a.ndim  # number of dimensions in the array

1

In [18]:
a.size  # size of an array is the no. of items 

5

In [19]:
a.shape

(5,)

In [20]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [22]:
type(my_matrix)

list

In [23]:
my_matrix.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [24]:
b=np.array(my_matrix)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
b.size

12

In [26]:
b.shape

(3, 4)

In [27]:
b.ndim

2

In [28]:
arr1= np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
arr1.ndim

3

In [30]:
arr1.dtype  # datatype of the elements 

dtype('int32')