In [1]:
import numpy as np

In [2]:
int1= 45

In [3]:
type(int1)

int

In [8]:
num1= np.array(int1)

In [10]:
print(num1)
print(type(num1))

45
<class 'numpy.ndarray'>


# NumPy 
NumPy is a Linear Algebra Library in Python and it is the holy grail and the main building block of Data Science using Python. Almost all the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

It is bound to several C libraries which makes NumPy one of the fastest libraries in Python.

We will learn the basics of NumPy, to get started we need to install it!

In [11]:
arr1 = np.array([])   # create an empty array
arr1

array([], dtype=float64)

In [12]:
type(arr1)

numpy.ndarray

In [14]:
arr2=np.array([])

In [15]:

my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [16]:
t=tuple(my_list)
print(type(t))

<class 'tuple'>


In [17]:
a=np.array(my_list)

In [18]:
a

array([1, 2, 3, 4, 5])

In [19]:
type(a)   # ndarray is number dimension array

numpy.ndarray

In [22]:
a.ndim

1

In [23]:
a.ndim  # number of dimensions in the array

1

In [25]:
a.size # size of an array is the no. of items 

5

In [26]:
a.shape # shape of array

(5,)

#### Arrays can be of n dimensions.


In [28]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] # list of lists
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [29]:
b= np.array(my_matrix)

In [30]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
# Array summary
print('The Dimension of array',b.ndim) # dimensions of given array

The Dimension of array 2


In [32]:
print('The size of array:',b.size) # Number of elements in array

The size of array: 12


In [33]:
print('The datatype of element:',b.dtype) # Datatype of elements in array

The datatype of element: int32


In [34]:
print('The type of structure:',type(b))

The type of structure: <class 'numpy.ndarray'>


In [35]:
print('The shape:',b.shape)

The shape: (3, 4)


## Built-in Methods

There are lots of built-in ways to generate Arrays

In [37]:
### Reshape function

In [41]:
arr1=np.array([1,2,3])

In [42]:
arr2=arr1.reshape((1,3,4))  # reshape function takes the new shape as its argument

ValueError: cannot reshape array of size 3 into shape (1,3,4)

In [ ]:
arr2

In [ ]:
arr2.shape

In [47]:
arr3 = arr1.reshape((3, 1))  # valid

In [48]:
arr3

array([[1],
       [2],
       [3]])

In [49]:
arr4 = arr3.reshape((3, 3,1))  # valid
arr4

ValueError: cannot reshape array of size 3 into shape (3,3,1)

In [50]:
arr2=arr1.reshape((1,3,4))  # reshape function takes the new shape as its argument

ValueError: cannot reshape array of size 3 into shape (1,3,4)

In [51]:
arr5=np.reshape(4,2,3)

TypeError: order must be str, not int

In [52]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr5 = np.reshape(arr, (2, 3))
print(arr5)

[[1 2 3]
 [4 5 6]]
