In [1]:
import numpy as np

In [2]:
int1= 45

In [3]:
type(int1)

int

In [8]:
num1= np.array(int1)

In [10]:
print(num1)
print(type(num1))

45
<class 'numpy.ndarray'>


# NumPy 
NumPy is a Linear Algebra Library in Python and it is the holy grail and the main building block of Data Science using Python. Almost all the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

It is bound to several C libraries which makes NumPy one of the fastest libraries in Python.

We will learn the basics of NumPy, to get started we need to install it!

In [11]:
arr1 = np.array([])   # create an empty array
arr1

array([], dtype=float64)

In [12]:
type(arr1)

numpy.ndarray

In [14]:
arr2=np.array([])

In [15]:

my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [16]:
t=tuple(my_list)
print(type(t))

<class 'tuple'>


In [17]:
a=np.array(my_list)

In [18]:
a

array([1, 2, 3, 4, 5])

In [19]:
type(a)   # ndarray is number dimension array

numpy.ndarray

In [22]:
a.ndim

1

In [23]:
a.ndim  # number of dimensions in the array

1

In [25]:
a.size # size of an array is the no. of items 

5

In [26]:
a.shape # shape of array

(5,)

#### Arrays can be of n dimensions.


In [28]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] # list of lists
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [29]:
b= np.array(my_matrix)

In [30]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
# Array summary
print('The Dimension of array',b.ndim) # dimensions of given array

The Dimension of array 2


In [32]:
print('The size of array:',b.size) # Number of elements in array

The size of array: 12


In [33]:
print('The datatype of element:',b.dtype) # Datatype of elements in array

The datatype of element: int32


In [34]:
print('The type of structure:',type(b))

The type of structure: <class 'numpy.ndarray'>


In [35]:
print('The shape:',b.shape)

The shape: (3, 4)


## Built-in Methods

There are lots of built-in ways to generate Arrays

In [37]:
### Reshape function

In [41]:
arr1=np.array([1,2,3])

In [42]:
arr2=arr1.reshape((1,3,4))  # reshape function takes the new shape as its argument

ValueError: cannot reshape array of size 3 into shape (1,3,4)

In [ ]:
arr2

In [ ]:
arr2.shape

In [47]:
arr3 = arr1.reshape((3, 1))  # valid

In [48]:
arr3

array([[1],
       [2],
       [3]])

In [49]:
arr4 = arr3.reshape((3, 3,1))  # valid
arr4

ValueError: cannot reshape array of size 3 into shape (3,3,1)

In [50]:
arr2=arr1.reshape((1,3,4))  # reshape function takes the new shape as its argument

ValueError: cannot reshape array of size 3 into shape (1,3,4)

In [51]:
arr5=np.reshape(4,2,3)

TypeError: order must be str, not int

In [52]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr5 = np.reshape(arr, (2, 3))
print(arr5)

[[1 2 3]
 [4 5 6]]


# arange

Return evenly spaced values within a given interval.

In [54]:
arr1=np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
arr2=np.arange(100,2,-4)
arr2

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24,  20,  16,  12,   8,   4])

In [56]:
np.arange(0,11,2) # start end and step

array([ 0,  2,  4,  6,  8, 10])

# zeros and ones

Generate arrays of zeros or ones

In [58]:
np.zeros(3) # Generates array in 1 dimension with all elements 0

array([0., 0., 0.])

In [59]:
np.zeros((5,5))  # Generates array in 2 diemnsions with all elements 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
np.ones(3) # Generates array of 1 dimension where all elements are 1

array([1., 1., 1.])

In [61]:
np.ones((4,5)) # Generates array of 3 dimensions where all elements are 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# linspace
Return evenly spaced numbers over a specified interval.

In [64]:
np.linspace(1,15)  # default 50 observations
# both the start and end are included in the array

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [65]:
np.linspace(5,25,10)  # equally spaced 10 values

array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
       16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ])

In [67]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [68]:
np.linspace(0,25, retstep=True) # Start # end (Here end is included) and default elements are 50

(array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
         2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
         5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
         7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
        10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
        12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
        15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
        17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
        20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
        22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ]),
 0.5102040816326531)

# eye

Creates an identity matrix

In [70]:
np.eye(5)   # generates 2d array of (5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
# Create an eye from a zeros array

In [72]:
### Broadcasting in an array

In [73]:
my_list = [1,2,3,4,5]
arr=np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [74]:
print(my_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [75]:
print(arr*3)

[ 3  6  9 12 15]


In [76]:
big_one=np.ones((3,4))
print(big_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [77]:
big_one.dtype

dtype('float64')

In [78]:
big_one * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [79]:
#### The ability to access each and every element of an array is known as Broadcasting.

In [80]:
bigger_one=big_one*6 - 2
bigger_one

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [81]:
bigger=np.array(big_one*3 - 0.4, dtype='int')
print(bigger)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [83]:
bigger.dtype

dtype('int32')

In [84]:
type(bigger)

numpy.ndarray

In [85]:
bigger.shape

(3, 4)

In [82]:
bigger/bigger

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [86]:
arr1 = np.arange(20)
1/arr1

C:\Users\Dell\AppData\Local\Temp\ipykernel_13868\3219800275.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr1


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [89]:
arr

array([1, 2, 3, 4, 5])

In [87]:
arr + arr

array([ 2,  4,  6,  8, 10])

In [88]:
arr ** arr

array([   1,    4,   27,  256, 3125])

# Use of Copy function

In [91]:
arr2 = arr1 # not recommended
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [92]:
arr2[:10] = 30  # using indexing/slicing to modify arr2
arr2

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [94]:
arr3 = arr1.copy() # generate a copy / creates a backup
arr3

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [95]:
arr3[15:] = 100
arr3

array([ 30,  30,  30,  30,  30,  30,  30,  30,  30,  30,  10,  11,  12,
        13,  14, 100, 100, 100, 100, 100])

## Random number generation

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [1]:
import numpy as np

In [2]:
np.random.rand(10)

array([0.82391795, 0.3185178 , 0.99051994, 0.71420405, 0.45875744,
       0.33275024, 0.46960119, 0.77725374, 0.91946095, 0.63740489])

In [3]:
np.random.rand()

0.597743114797012

In [4]:
np.random.rand(10).reshape((2,5))

array([[0.69222133, 0.34690936, 0.64453876, 0.89958341, 0.98728373],
       [0.59460469, 0.01059415, 0.72868985, 0.04190108, 0.08630279]])

In [5]:
# Creating array from uniform distribution
new_arr=np.random.rand(5,3)
# 2 dimensional array of shape (5,3)

In [7]:
new_arr

array([[0.17149387, 0.67407178, 0.33145354],
       [0.66859468, 0.17227768, 0.06986143],
       [0.41257401, 0.30385821, 0.64373562],
       [0.2486592 , 0.43121235, 0.76563962],
       [0.50646456, 0.53848902, 0.20877173]])

In [6]:
np.random.rand(3,3)

array([[0.90039693, 0.03555176, 0.56213173],
       [0.96012163, 0.30193358, 0.51477513],
       [0.41581339, 0.45223435, 0.83366858]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
# For randn, random numbbers generated will be in approximately -3 to +3 range.

In [9]:
arr1=np.random.randn(50)  # 50 observations from std normal distribution
arr1

array([ 1.13145913,  0.68225186,  0.09707765, -1.07682186,  0.43776786,
        1.0643423 , -0.23599664, -0.50984901,  0.5858414 ,  1.23188023,
        0.54486467, -0.2849452 , -0.22398982, -1.31414431, -0.60324535,
       -0.62398949, -0.89621195, -0.80207431, -1.23232373,  2.32240968,
        3.09155736,  0.3064436 , -0.45883836,  0.65792206,  1.0516462 ,
       -0.65901882, -0.01341928,  0.58607123, -0.03474667,  0.8994893 ,
        0.45183484, -0.32869666, -1.3225872 ,  0.26455504,  0.46262135,
        0.7184461 ,  1.41335187,  1.09343013,  0.47042218,  0.50535794,
        0.37751226, -0.53423797, -0.16356563, -0.00317443, -2.0929329 ,
       -1.24464976, -0.66445662, -1.26438338, -0.98135934,  1.31456384])

In [10]:
max(arr1)

3.091557363798405

In [ ]:
min(arr1)

In [12]:
np.random.randn(3,3)

array([[ 1.14624742, -0.11536365,  0.65803131],
       [ 2.43589315, -0.88205903,  1.03401424],
       [-1.01829755, -0.47433601, -0.71047967]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [14]:
np.random.randint(1000,9999) 
# third argument is no. of values. default =1 value

6003

In [3]:
np.random.randint(10,99) 
# third argument is no. of values. default =1 value

81

In [15]:
np.random.randint(1,100,10)

array([76, 46, 33, 22, 23, 60, 73, 76,  6, 17])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [2]:
import numpy as np

In [3]:
arr = np.arange(20)
ranarr = np.random.randint(0,100,10)

In [4]:
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[46 97 71 40 29 77 54 26 81 37]


### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [5]:
ranarr.max() # highest element of the array

97

In [6]:
arr.max()

19

In [7]:
ranarr.argmax() ## Index location of highest element

1

In [8]:
ranarr.min() # Gives the lowest element of array

26

In [9]:
ranarr.argmin() # Index location of lowest element

7

In [10]:
ran2=ranarr.reshape(2,5)

In [11]:
ran2

array([[46, 97, 71, 40, 29],
       [77, 54, 26, 81, 37]])

In [12]:
ran2.argmax()

1

In [13]:
ran2.max()

97

In [15]:
ran3=ranarr.reshape(5,2)

In [16]:
ran3

array([[46, 97],
       [71, 40],
       [29, 77],
       [54, 26],
       [81, 37]])

# ----------------------------

# rmpty array

In [23]:
arr1= np.array([])

In [24]:
arr1

array([], dtype=float64)